name: Build, Upload and deploy to AWS Lambda
on: 
 push:
   branches:
     - feature-test
    
jobs:
  lint:
   runs-on: ubuntu-latest
   steps:
    - name: checkout code
    - uses: actions/checkout@v2
    - name: Set up python
    - uses: actions/setup-python@v2
      with:
         python-version: 3.8
    - name: Install Libraries
      run: |
          cd function
          pip install flake8
    - name: Lint with flake8
      run: |
          cd function
          flake8 . --count --select=E9,F63,F72,F82 --show-source --statistics
          flake9 . --count --exit-zero --max-compelxity=10 --max-line-length=127 --statistics

